### ISSUE TITLE
Symbol’s value as variable is void: print-message

### ISSUE THREAD

**Issue by jsilve24** [seanfarley/emacs-bitwarden#10]
Thank you for putting this package together. 
I am trying to set this package up but I am getting the message

`Symbol’s value as variable is void: print-message [2 times]`

Whenever I try to login. 

Here is my configuration. 

```
(setq bitwarden-user "foo@gmail.com")
(setq bitwarden-automatic-unlock
      (let* ((matches (auth-source-search :user "foo@gmail.com"
					  :host "bitwarden.foo"
					  :require '(:secret)
					  :max 1))
	     (entry (nth 0 matches)))
	(plist-get entry :secret)))
(bitwarden-auth-source-enable)
```

I also have a line in my authinfo that reads
`machine bitwarden.foo login foo@gmail.com password XXX`

**Comment by seanfarley** [comment]
Thanks for the report!

Let's try a few things first. Can you evaluate your `let` statement and get the expected result?

```lisp
(let* ((matches (auth-source-search :user "foo@gmail.com"
					  :host "bitwarden.foo"
					  :require '(:secret)
					  :max 1))
	     (entry (nth 0 matches)))
	(plist-get entry :secret))
```

Second, can you log in via the command line (without any emacs) and query your passwords?

**Comment by jsilve24** [comment]
So yes to the first question. The let statement works as expected.

Regarding the command line (first I feel silly not already trying that) -- yes BUT I also needed to pass an API key client_secret which I found by following these instructions: <https://bitwarden.com/help/personal-api-key/>

I notice that in my configuration password XXX is my password but there is nowhere that I am passing the API key...

**Comment by jsilve24** [comment]
On the command line the following call logs me in

bw login foo@gmail.com 'XXX' --code YYY

**Comment by seanfarley** [comment]
Hmm, did the command line change and I not notice it yet? Let me see if there are any updates and try on my end. You shouldn't need the api key, by the way

**Comment by seanfarley** [comment]
I haven't been able to reproduce this so it's been a challenge to see what's wrong :-(

**Comment by jsilve24** [comment]
Ya sorry I have not been much help. Laptop died and tried to recover.

Sent From My Mobile Device
________________________________

**Comment by seanfarley** [comment]
I see a few spots in the code where `print-message` could be nil. Could you try running `toggle-debug-on-error` and get a backtrace next time this happens?

**Comment by jsilve24** [comment]
Hi @seanfarley Sorry for the delay. Finally got my new laptop up and running. 

I found this issue that is of relevance and explains the API key client_secret issues: https://github.com/bitwarden/cli/issues/383 it looks like this is a new-ish issue that is here to stay. Would likely be good to build in ability to pass API client_secret to emacs-bitwarden.

**Comment by jsilve24** [comment]
And here is the backtrace from running bitwarden-login


Debugger entered--Lisp error: (void-variable print-message)
  (bitwarden--login-proc-filter proc string print-message)
  (lambda (proc string) (bitwarden--login-proc-filter proc string print-message))(#<process bitwarden> "? Additional authentication required.\nAPI key clie...")

**Comment by seanfarley** [comment]
Aha, thanks for figuring out the hard part! Is this only happening for non-self-hosted servers? For example, I self-host the rust port of the bitwarden server and haven't run into this.

**Comment by jsilve24** [comment]
That would be my guess but I am not sure. But reading through the linked issue that would be a solid guess

Sent From My Mobile Device
________________________________
