### ISSUE TITLE
I get an error for (bitwarden-login)

### ISSUE THREAD

**Issue by zoechi** [seanfarley/emacs-bitwarden#5]
```lisp
(setq bitwarden-user "name@example.com")
(unless (bitwarden-logged-in-p)
    (bitwarden-login))
```
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  make-process(:name "bitwarden" :buffer nil :connection-type pipe :command ("/usr/bin/bw" "login" "name@example.com" nil) :filter #f(compiled-function (proc string) #<bytecode 0x13d4e3109a540c09>))
  bitwarden--raw-unlock(("login" "guenter@gzoechbauer.com" nil) nil)
  bitwarden-login()
  (if (bitwarden-logged-in-p) nil (bitwarden-login))
  eval((if (bitwarden-logged-in-p) nil (bitwarden-login)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
Any idea what could be wrong?

I'm using bitwarden native cli (not the Node one)

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-02-12

**Comment by zoechi** [comment]
This might have to do with the checks of `bitwarden-logged-in-p` and `bitwarden-unlocked-p`
The code seems to check if the hash exists, but it should call out to `bw`
`bw login --check` and `bw unlock --check`
If I call `(bitwarden-lock)` at least `(bitwarden-unlock)` works. 
I just need to login outside of emacs.

**Comment by seanfarley** [comment]
Oh, I was unaware of the a native cli (only of the node one). You're totally right, I use a dirty (but fast) check for the hash in what I'm assuming is the node-cli settings location for the hash. Thanks for the report!

**Comment by seanfarley** [comment]
By the way, do you know if the two cli's are any different?

**Comment by zoechi** [comment]
There seems to be an issue with `bitwarden--auto-cmd`.
When bw is unlocked, all is fine.
When I call `bitwarden-lock` and then `bitwarden-getpass`, the call returns without result while I haven't yet filled the password.
Seems `bitwarden--auto-cmd` goes asnyc somewhere.

**Comment by seanfarley** [comment]
Hopefully, this is fixed now with the merged pullrequest. If not, let's open a new issue.

**Comment by zoechi** [comment]
Thanks a lot 👍 
I'll check as soon as I get back to my private PC. Might take a while though...
